Fix byte-compile warning
```
Error: custom-declare-variable *** docstring
has wrong usage of unescaped single quotes (use \= or different quoting)
```
Introduced probably in Emacs 29